apiVersion: v1
kind: ConfigMap
metadata:
  name: signalr-app-config
  labels:
    app: signalr-app
data:
  # API Configuration
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  
  # Frontend Configuration
  REACT_APP_API_URL: "http://signalr-api-service/api"
  REACT_APP_SIGNALR_URL: "http://signalr-api-service"
  
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "http://signalr-frontend-service,https://your-domain.com"