apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signalr-app

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app: signalr-app
  version: v1.0.0

images:
  - name: signalr-api
    newTag: latest
  - name: signalr-frontend
    newTag: latest